// This file is automatically generated. Do not edit it directly.
// Regenerate with: supabase gen types typescript --project-id jxnbgqjivrumvrypdkhd
// Fonte de verdade do schema do projeto Supabase (schema remoto "fase1a").
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_decision_log: {
        Row: {
          created_at: string | null
          id: string
          job_id: string | null
          provider: string | null
          tool_called: string | null
          tool_input: Json | null
          tool_output: Json | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          job_id?: string | null
          provider?: string | null
          tool_called?: string | null
          tool_input?: Json | null
          tool_output?: Json | null
        }
        Update: {
          created_at?: string | null
          id?: string
          job_id?: string | null
          provider?: string | null
          tool_called?: string | null
          tool_input?: Json | null
          tool_output?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_decision_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "publish_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor: string
          created_at: string
          detail: Json
          id: string
          seller_id: string
          target: string | null
        }
        Insert: {
          action: string
          actor?: string
          created_at?: string
          detail?: Json
          id?: string
          seller_id: string
          target?: string | null
        }
        Update: {
          action?: string
          actor?: string
          created_at?: string
          detail?: Json
          id?: string
          seller_id?: string
          target?: string | null
        }
        Relationships: []
      }
      credit_packs: {
        Row: {
          credits: number
          id: string
          name: string
          price_cents: number
        }
        Insert: {
          credits: number
          id?: string
          name: string
          price_cents: number
        }
        Update: {
          credits?: number
          id?: string
          name?: string
          price_cents?: number
        }
        Relationships: []
      }
      marketplace_accounts: {
        Row: {
          access_token_encrypted: string
          created_at: string | null
          external_account_id: string
          id: string
          marketplace: string
          refresh_token_encrypted: string
          seller_id: string
          status: string
          token_expires_at: string
        }
        Insert: {
          access_token_encrypted: string
          created_at?: string | null
          external_account_id: string
          id?: string
          marketplace: string
          refresh_token_encrypted: string
          seller_id: string
          status?: string
          token_expires_at: string
        }
        Update: {
          access_token_encrypted?: string
          created_at?: string | null
          external_account_id?: string
          id?: string
          marketplace?: string
          refresh_token_encrypted?: string
          seller_id?: string
          status?: string
          token_expires_at?: string
        }
        Relationships: []
      }
      oauth_states: {
        Row: {
          code_verifier: string
          created_at: string
          expires_at: string
          seller_id: string
          state: string
        }
        Insert: {
          code_verifier: string
          created_at?: string
          expires_at?: string
          seller_id: string
          state: string
        }
        Update: {
          code_verifier?: string
          created_at?: string
          expires_at?: string
          seller_id?: string
          state?: string
        }
        Relationships: []
      }
      publish_jobs: {
        Row: {
          actual_token_cost_cents: number | null
          ai_output: Json | null
          confidence_score: number | null
          created_at: string | null
          error_message: string | null
          id: string
          processed_at: string | null
          seller_id: string
          source_product_id: string
          status: string
          target_account_ids: string[]
        }
        Insert: {
          actual_token_cost_cents?: number | null
          ai_output?: Json | null
          confidence_score?: number | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          processed_at?: string | null
          seller_id: string
          source_product_id: string
          status?: string
          target_account_ids: string[]
        }
        Update: {
          actual_token_cost_cents?: number | null
          ai_output?: Json | null
          confidence_score?: number | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          processed_at?: string | null
          seller_id?: string
          source_product_id?: string
          status?: string
          target_account_ids?: string[]
        }
        Relationships: []
      }
      seller_ai_preferences: {
        Row: {
          acknowledged_at: string | null
          acknowledged_performance_risk: boolean
          created_at: string | null
          model_name: string
          own_api_key_encrypted: string | null
          provider: string
          seller_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_performance_risk?: boolean
          created_at?: string | null
          model_name?: string
          own_api_key_encrypted?: string | null
          provider?: string
          seller_id: string
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_performance_risk?: boolean
          created_at?: string | null
          model_name?: string
          own_api_key_encrypted?: string | null
          provider?: string
          seller_id?: string
        }
        Relationships: []
      }
      seller_credits: {
        Row: {
          credits_remaining: number
          cycle_reset_at: string
          plan_id: string | null
          seller_id: string
        }
        Insert: {
          credits_remaining?: number
          cycle_reset_at?: string
          plan_id?: string | null
          seller_id: string
        }
        Update: {
          credits_remaining?: number
          cycle_reset_at?: string
          plan_id?: string | null
          seller_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "seller_credits_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "subscription_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription_plans: {
        Row: {
          courtesy_credits: number
          id: string
          max_accounts: number
          name: string
          price_cents: number
        }
        Insert: {
          courtesy_credits?: number
          id?: string
          max_accounts: number
          name: string
          price_cents: number
        }
        Update: {
          courtesy_credits?: number
          id?: string
          max_accounts?: number
          name?: string
          price_cents?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      meli_accounts_needing_refresh: {
        Args: { p_threshold_seconds: number }
        Returns: {
          account_id: string
          external_account_id: string
          refresh_token: string
        }[]
      }
      meli_apply_refresh: {
        Args: {
          p_access: string
          p_account_id: string
          p_expires_at: string
          p_refresh: string
        }
        Returns: undefined
      }
      meli_get_access_token: {
        Args: { p_seller_id: string }
        Returns: {
          access_token: string
          account_id: string
          external_account_id: string
          status: string
          token_expires_at: string
        }[]
      }
      meli_get_refresh_token: {
        Args: { p_account_id: string }
        Returns: string
      }
      meli_mark_reauth: { Args: { p_account_id: string }; Returns: undefined }
      meli_store_account: {
        Args: {
          p_access: string
          p_expires_at: string
          p_external_account_id: string
          p_refresh: string
          p_seller_id: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
